export const songData = [
  {
    level: 1,
    sequence: 1,
    title: "Hot Cross Buns",
    image: "images/01-hot-cross-buns.pdf",
    youtube: "https://youtu.be/3xDuF9zwbGU",
    fbRef: "101",
  },
  {
    level: 1,
    sequence: 2,
    title: "Mary Had A Little Lamb",
    image: "images/01-mary-had-a-little-lamb.pdf",
    youtube: "https://youtu.be/grDcfEkEO6I",
    fbRef: "102",
  },
  {
    level: 1,
    sequence: 3,
    title: "Au Claire de la Lune",
    image: "images/01-au-claire-de-la-lune.pdf",
    youtube: "https://youtu.be/1wXyVQZb1vU",
    fbRef: "103",
  },
  {
    level: 1,
    sequence: 4,
    title: "Jingle Bells",
    image: "images/01-jingle-bells.pdf",
    youtube: "https://youtu.be/heYQZ1XjY_M",
    fbRef: "104",
  },
  {
    level: 1,
    sequence: 5,
    title: "Rain, Rain, Go Away",
    image: "images/01-rain-rain.pdf",
    youtube: "https://youtu.be/bUSKOnnEkRI",
    fbRef: "105",
  },
  {
    level: 1,
    sequence: 6,
    title: "A Tisket, A Tasket",
    image: "images/01-tisket-tasket",
    youtube: "https://youtu.be/u3ggzUnmwoI",
    fbRef: "106",
  },
  {
    level: 1,
    sequence: 7,
    title: "Ode to Joy",
    image: "images/01-ode-to-joy",
    youtube: "https://youtu.be/Ecx6-i9Uo98",
    fbRef: "107",
  },
  {
    level: 1,
    sequence: 8,
    title: "Sweetly Sings the Donkey",
    image: "images/01-sweetly-sings-the-donkey.pdf",
    youtube: "https://youtu.be/4u8x60n98e0",
    fbRef: "108",
  },
  {
    level: 1,
    sequence: 9,
    title: "Go Tell Aunt Rhodie",
    image: "images/01-go-tell-aunt-rhodie.pdf",
    youtube: "https://youtu.be/ZgaeiGv81XA",
    fbRef: "109",
  },
  {
    level: 1,
    sequence: 10,
    title: "Banks of the Ohio",
    image: "images/01-banks-of-the-ohio",
    youtube: "https://youtu.be/rvptLO7993g",
    fbRef: "110",
  },
  {
    level: 2,
    sequence: 1,
    title: "Pop! Goes the Weasel",
    image: "images/02-pop-goes-the-weasel.pdf",
    youtube: "https://youtu.be/TiEeIBFmDT4",
    fbRef: "201",
  },
  {
    level: 2,
    sequence: 2,
    title: "Row, Row, Row Your Boat",
    image: "images/02-row-row-row-your-boat.pdf",
    youtube: "https://youtu.be/devbe8wYHPE",
    fbRef: "202",
  },
  {
    level: 2,
    sequence: 3,
    title: "Camptown Races",
    image: "images/02-camptown-races.pdf",
    youtube: "https://youtu.be/33a5mKYnPtQ",
    fbRef: "203",
  },
  {
    level: 2,
    sequence: 4,
    title: "Swan Lake",
    image: "images/02-swan-lake.pdf",
    youtube: "https://youtu.be/_x9tbgtcyms",
    fbRef: "204",
  },
  {
    level: 2,
    sequence: 5,
    title: "Auld Lang Syne",
    image: "images/02-auld-lang-syne.pdf",
    youtube: "https://youtu.be/w70ro945CgI",
    fbRef: "205",
  },
  {
    level: 2,
    sequence: 6,
    title: "Bridal March",
    image: "images/02-bridal-march.pdf",
    youtube: "https://youtu.be/FinbnEIVU4U",
    fbRef: "206",
  },
  {
    level: 2,
    sequence: 7,
    title: "London Bridge",
    image: "images/02-london-bridge.pdf",
    youtube: "https://youtu.be/ljUeJVxOWTY",
    fbRef: "207",
  },
  {
    level: 2,
    sequence: 8,
    title: "Five Fat Turkeys",
    image: "images/08-five-fat-turkeys.pdf",
    youtube: "https://youtu.be/9BYO15fcPiQ",
    fbRef: "208",
  },
  {
    level: 2,
    sequence: 9,
    title: "Yankee Doodle",
    image: "images/09-yankee-doodle.pdf",
    youtube: "https://youtu.be/dxkZ-2FkLLw",
    fbRef: "209",
  },
  {
    level: 2,
    sequence: 10,
    title: "Old MacDonald",
    image: "images/02-old-macdonald.pdf",
    youtube: "https://youtu.be/zUWiinHcVd8",
    fbRef: "210",
  },
  {
    level: 2,
    sequence: 11,
    title: "Twinkle, Twinkle, Little Star",
    image: "images/02-twinkle-twinkle.pdf",
    youtube: "https://youtu.be/5z5ESuEmG-k",
    fbRef: "211",
  },
  {
    level: 3,
    sequence: 1,
    title: "The Baby Bumble Bee",
    image: "images/03-baby-bumble-bee.pdf",
    youtube: "https://youtu.be/d1n9IAF2Img",
    fbRef: "301",
  },
  {
    level: 3,
    sequence: 2,
    title: "Happy Birthday",
    image: "images/03-happy-birthday.pdf",
    youtube: "https://youtu.be/3cRVwanUKqs",
    fbRef: "302",
  },
  {
    level: 3,
    sequence: 3,
    title: "BINGO",
    image: "images/03-bingo.pdf",
    youtube: "https://youtu.be/5uQ-rwRyE_E",
    fbRef: "303",
  },
  {
    level: 3,
    sequence: 4,
    title: "Ode to Joy (LH only)",
    image: "images/03-ode-to-joy-lefty.pdf",
    youtube: "https://youtu.be/Y40jIlPNS-E",
    fbRef: "304",
  },
  {
    level: 3,
    sequence: 5,
    title: "Aloutte",
    image: "images/03-alouette.pdf",
    youtube: "https://youtu.be/9pwv-b_SpNU",
    fbRef: "305",
  },
  {
    level: 3,
    sequence: 6,
    title: "Three Jolly Fishermen",
    image: "images/03-jolly-fisherman.pdf",
    youtube: "https://youtu.be/oekfdQMZZ-Y",
    fbRef: "306",
  },
  {
    level: 3,
    sequence: 7,
    title: "Row, Row, Row Your Boat",
    image: "images/03-row-row-row-your-boat.pdf",
    youtube: "https://youtu.be/0Go_0qoeMC8",
    fbRef: "307",
  },
  {
    level: 3,
    sequence: 8,
    title: "Turkey in the Straw",
    image: "images/03-turkey-in-the-straw.pdf",
    youtube: "https://youtu.be/VBDS8WRmDMI",
    fbRef: "308",
  },
  {
    level: 3,
    sequence: 9,
    title: "Banks of the Ohio",
    image: "images/03-banks-of-the-ohio.pdf",
    youtube: "https://youtu.be/hBefLxKf5To",
    fbRef: "309",
  },
  {
    level: 3,
    sequence: 10,
    title: "Ode to Joy",
    image: "images/03-ode-to-joy.pdf",
    youtube: "https://youtu.be/oqT5S3ZpqFI",
    fbRef: "310",
  },
  {
    level: 3,
    sequence: 11,
    title: "Jingle Bells",
    image: "images/03-jingle-bells.pdf",
    youtube: "https://youtu.be/mBPV8r9r1Ng",
    fbRef: "311",
  },
];
